spring:
  sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    driverClassName: org.postgresql.Driver
    username: inventory_user
    password: inventory_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

  